### ISSUE TITLE
Cannot push data to server

### ISSUE THREAD

**Issue by jonathan-yin2020** [shimoncohen/GEEDocker#2]
[2020-08-10 21:39:38] Warning: No status message returned from 
  request: http://localhost.localdomain/geserve/StreamPush?Cmd=Ping&Host=localhost.localdomain
[2020-08-10 21:39:38] Warning: Unable to contact stream data server.

**Comment by shimoncohen** [comment]
Thank you for the issue. Can you please explain in detail how you got this error?
Please describe how to re-create it and add images if possible.

**Comment by jonathan-yin2020** [comment]
I followed your instruction to build the server. After I define a database in Fusion with the tutorial data, I tried to push it to Google Earth Enterprise Server. Then I received the Warning: No status message returned from request: http://localhost.localdomain/geserve/StreamPush?Cmd=Ping&Host=localhost.localdomain. I am new to docker, let me know if you need other information. I am just wondering if I need to make any change in your code to make this work in my environment .

**Comment by shimoncohen** [comment]
Ok, first make sure the server docker is up and running. You may check this by running the following:
```
$ docker container ls
```
If you see servercontainer listed, then it is running.

If the server is running and you are still getting this issue, from what i understand, you probably didn't set the Stream URL in the server associations manager to the correct server URL. Currently the server runs on localhost:8081 (unless you changed the port), so it should look something like this:
![Screenshot from 2020-08-11 02-07-14](https://user-images.githubusercontent.com/33935191/89839841-675d9980-db77-11ea-9bef-ca9c33884043.png)
To get there click Tools -> Server Associations Manager.

Please let me know if this solves your issue.

**Comment by jonathan-yin2020** [comment]
The Server Associations Manager was the step I missed!! Thank you so much for sharing and it works very well.

**Comment by shimoncohen** [comment]
Glad to hear, you are welcome.
And thank you!
